# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(993, 713)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 671, 461))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 540, 291, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 600, 291, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(710, 10, 251, 241))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(710, 290, 251, 241))
        self.groupBox_2.setObjectName("groupBox_2")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(20, 0, 481, 51))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 993, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionadd = QtWidgets.QAction(MainWindow)
        self.actionadd.setObjectName("actionadd")
        self.actiondel = QtWidgets.QAction(MainWindow)
        self.actiondel.setObjectName("actiondel")
        self.actionfind = QtWidgets.QAction(MainWindow)
        self.actionfind.setObjectName("actionfind")
        self.actionadd_2 = QtWidgets.QAction(MainWindow)
        self.actionadd_2.setObjectName("actionadd_2")
        self.actiondel_2 = QtWidgets.QAction(MainWindow)
        self.actiondel_2.setObjectName("actiondel_2")
        self.actionfind_2 = QtWidgets.QAction(MainWindow)
        self.actionfind_2.setObjectName("actionfind_2")
        self.menu.addAction(self.actionadd)
        self.menu.addAction(self.actiondel)
        self.menu.addAction(self.actionfind)
        self.menu_2.addAction(self.actionadd_2)
        self.menu_2.addAction(self.actiondel_2)
        self.menu_2.addAction(self.actionfind_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FaceCheckSystem"))
        self.label.setText(_translate("MainWindow", "图像显示"))
        self.pushButton.setText(_translate("MainWindow", "开始签到"))
        self.pushButton_2.setText(_translate("MainWindow", "停止签到"))
        self.groupBox.setTitle(_translate("MainWindow", "签到统计"))
        self.groupBox_2.setTitle(_translate("MainWindow", "检测信息"))
        self.menu.setTitle(_translate("MainWindow", "班级管理"))
        self.menu_2.setTitle(_translate("MainWindow", "学生管理"))
        self.actionadd.setText(_translate("MainWindow", "增"))
        self.actiondel.setText(_translate("MainWindow", "删"))
        self.actionfind.setText(_translate("MainWindow", "查"))
        self.actionadd_2.setText(_translate("MainWindow", "增"))
        self.actiondel_2.setText(_translate("MainWindow", "删"))
        self.actionfind_2.setText(_translate("MainWindow", "查"))
