# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(993, 713)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 671, 461))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 540, 291, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 600, 291, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(710, 10, 251, 241))
        self.groupBox.setObjectName("groupBox")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 20, 231, 211))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(710, 290, 251, 371))
        self.groupBox_2.setObjectName("groupBox_2")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(10, 40, 231, 321))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(20, 0, 481, 51))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 993, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionaddclass = QtWidgets.QAction(MainWindow)
        self.actionaddclass.setObjectName("actionaddclass")
        self.actiondelclass = QtWidgets.QAction(MainWindow)
        self.actiondelclass.setObjectName("actiondelclass")
        self.actionfindclass = QtWidgets.QAction(MainWindow)
        self.actionfindclass.setObjectName("actionfindclass")
        self.actionaddStu = QtWidgets.QAction(MainWindow)
        self.actionaddStu.setObjectName("actionaddStu")
        self.actiondelStu = QtWidgets.QAction(MainWindow)
        self.actiondelStu.setObjectName("actiondelStu")
        self.actionfindStu = QtWidgets.QAction(MainWindow)
        self.actionfindStu.setObjectName("actionfindStu")
        self.menu.addAction(self.actionaddclass)
        self.menu.addAction(self.actiondelclass)
        self.menu.addAction(self.actionfindclass)
        self.menu_2.addAction(self.actionaddStu)
        self.menu_2.addAction(self.actiondelStu)
        self.menu_2.addAction(self.actionfindStu)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FaceCheckSystem"))
        self.label.setText(_translate("MainWindow", "图像显示"))
        self.pushButton.setText(_translate("MainWindow", "开始签到"))
        self.pushButton_2.setText(_translate("MainWindow", "停止签到"))
        self.groupBox.setTitle(_translate("MainWindow", "签到统计"))
        self.groupBox_2.setTitle(_translate("MainWindow", "检测信息"))
        self.menu.setTitle(_translate("MainWindow", "班级管理"))
        self.menu_2.setTitle(_translate("MainWindow", "学生管理"))
        self.actionaddclass.setText(_translate("MainWindow", "增"))
        self.actiondelclass.setText(_translate("MainWindow", "删"))
        self.actionfindclass.setText(_translate("MainWindow", "查"))
        self.actionaddStu.setText(_translate("MainWindow", "增"))
        self.actiondelStu.setText(_translate("MainWindow", "删"))
        self.actionfindStu.setText(_translate("MainWindow", "查"))
